### ISSUE TITLE
Unresponsive PHP process safe guard

### ISSUE THREAD

**Issue by ajmichels** [SublimeLinter/SublimeLinter-phpcs#13] opened 2016-03-15 14:22 UTC
There is a known issue in the `phpcs` linter which results in a runaway PHP process that never terminates and uses all available CPU. Ideally this issue would be resolved in `phpcs` itself but hopefully we can introduce some sort of safe guard for this within this SublimeLinter package. 

This issue is discussed at length in SublimeLinter/SublimeLinter-php#12

There is currently an open issue for this at squizlabs/PHP_CodeSniffer#618

**Comment by plashenkov** [comment] 2016-08-30 20:44
There is no guarantee that PHP_CodeSniffer will work correctly in all situations. If I understand correctly, it was designed to check code style on a valid code. They try to fix some particular situations where it hangs, but there can be another hundred. Thus we really need to prelint file using `php -l` before passing it to phpcs.

Maybe it is better to write a custom plugin (some kind of SublimeLinter-contrib-phpcs) which checks a file using `php -l` first, and then `phpcs`. Is it possible or SublimeLinter does not allow to do that (use multiple commands in one lint process)?

**Comment by joehoyle** [comment] 2017-09-21 16:01
I'm not sure it's due to syntax errors, I think it's some upstream bug in PHPCS that causes it to hang. See https://github.com/AtomLinter/linter-phpcs/issues/239 for the same issue in Atom. The parent process, though a hack, is the best one to kill it on a timeout. +1 for adding this nasty hack to this linter.

**Comment by kaste** [comment] 2018-04-20 07:49
Is this still a thing for say phpcs > 3.0? Solve it or close it? And, erm, what is a good value here. 10 seconds for live/background linting. Really?

**Comment by knifesk** [comment] 2018-06-25 20:31
@kaste still a thing... been dealing with this problem all day now

**Comment by kaste** [comment] 2018-06-25 20:35
Try the kill old processes switch/setting. You'll find it in the SublimeLinter settings.

**Comment by knifesk** [comment] 2018-06-25 20:40
Ohh cool! I just enabled that feature.. will see if it solves the problem... 

Thank you very much kaste! I wasted my entire morning reinstalling all my sublime instance to end up with the same problem haha!

**Closed** 2018-12-18 19:59 UTC
Labels: bug, enhancement, waiting for response
